version: '3.8'

services:
  api_gateway:
    build: .
    container_name: api_gateway
    ports:
      - "8500:8500"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - DB_NAME=mydatabase
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    networks:
      - backend

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

volumes:
  mongo_data:

networks:
  backend:
    driver: bridge
